### ISSUE TITLE
Extract concepts from raw strings

### ISSUE THREAD

**Issue by hrzhuang** [JacquesCarette/Drasil#3402] opened 2023-05-10 14:17 UTC
There are many potential concepts that we currently use as raw strings. It would be beneficial to look through all of the examples to extract these into concepts.

Instances:
* [See discussion](https://github.com/JacquesCarette/Drasil/pull/3398#discussion_r1189162689)

Note that this is different than #3252; that issue is responsible for using existing concepts, while this one is responsible for identifying/creating new ones!

**Comment by samm82** [comment] 2024-05-01 02:29
Duplicate of #3698

**Closed by samm82** 2024-05-01 02:29 UTC
Labels: enhancement, Low Priority, newcomers
