### ISSUE TITLE
Differences in Table of Symbols in GlassBR SRS

### ISSUE THREAD

**Issue by samm82** [JacquesCarette/Drasil#824] opened 2018-07-11 14:27 UTC
The following need to be fixed in caseStudies:
- [x] Fix no line breaks in caseStudies
  - **Note:** "My first though is to use the p{width} specifier in the LaTeX listing of column justification. You could also look at the generated LaTeX to see how it is done there."
- [x] Define SD<sub>x</sub>, SD<sub>y</sub>, and SD<sub>z</sub> explicitly in caseStudies
- [x] Define the following in caseStudies: AR<sub>max</sub>, AR, GTF, LDF, LR, LSF, NFL, TNT
- [x] Change units for a, b, and h to meters in caseStudies
- [x] Change "second" to "s" in caseStudies
- [x] Swap "B" and "b" in caseStudies
- [x] Change "Explosive Mass..." to "Explosive mass..." in caseStudies

![table of symbols](https://user-images.githubusercontent.com/35857611/42576860-5153c5d0-84f1-11e8-9567-b3eb448fe659.png)

**Comment by smiths** [comment] 2018-07-11 14:54
Thank  you @samm82 for the thorough analysis of differences.  I've reproduced the list below and I'll edit in my comments.

- [ ] The "Unit" column is the second one in caseStudies, and the third in Drasil [Yes, these are different, but we don't need to bother changing either of them.  The ordering of the columns is essential arbitrary.  When Drasil is complete changing the order to the user's preference will be a user configurable parameter (part of the recipe).]
- [ ] The column headers are bold in caseStudies, and "Units" in Drasil is "Unit" in caseStudies [Similar to the previous point, this is a stylistic choice.  One isn't necessarily better than the other.  We don't need to change either example to match the other.]
- [ ] Drasil doesn't display when a symbol is "unitless" [I would prefer if Drasil displayed unitless symbols, but I vaguely remember a conversation with @JacquesCarette and @szymczdm about this and I'm not sure they liked showing unitless.  To me if nothing is present it could be because the author forgot to include the units.  It doesn't automatically imply unitless to me.  @samm82, can you create an issue in the Drasil repo to discuss this point with @szymczdm and @JacquesCarette?]
- [ ] There are no line breaks in caseStudies [I'm surprised that the text just runs of the page in the case study example.  I don't know why that wasn't previously fixed?  Regardless, can you please fix this.  My first though is to use the p{width} specifier in the LaTeX listing of column justification.  You could also look at the generated LaTeX to see how it is done there.]
- [ ] SD<sub>x</sub>, SD<sub>y</sub>, and SD<sub>z</sub> are explicitly defined in Drasil, but listed as part of SD in caseStudies [I don't have a strong preference on this, but the Drasil version matches our current approach, which is to make every symbol global.  Please change the case study to match Drasil.]
- [ ] The following are defined in Drasil but not in caseStudies: **_AR<sub>max</sub>_**, AR, GTF, **_LDF_**, **_LR_**, **_LSF_**, **_NFL_**, TNT [These are all defined in the case study, but in the table of abbreviations and acronyms.  In hindsight, these symbols make more sense in the table of symbols than the table of abbreviations and acronyms.  I think going forward we should put all mathematical symbols in the table of symbols, even if the symbol is inspired by an acronym.  The table of abbreviations and acronyms can be reserved for English language abbreviations and acronyms.  That is, the table of acronyms can be reserved for things that appear in text.  Alternatively, the symbols could show up as symbols and as acronyms.  I believe @szymczdm and @JacquesCarette and I have previously discussed the difference between symbols and acronyms.  For now, I think it makes the most sense for you to add the symbols you mentioned (AR etc) to the table of symbols.  Have the table of abbreviations and acronyms match the Drasil version.]
- [ ] The units for a, b, and h are meters in Drasil and millimeters in caseStudies [Please change the units in the case study to meters.  Implicit unit conversions cause way too many headaches.  We should specify everything as standard SI units (m, kg, s, etc.).]
- [ ] The unit "second" is spelled out in caseStudies [Please change this to match the Drasil version.]
- [ ] "B" and "b" have switched locations between Drasil and caseStudies [Drasil automates the sort, while the case study version was done by a human.  Use the Drasil version for both.]
- [ ] w<sub>TNT</sub> is defined as "Explosive mass..." in Drasil and "Explosive Mass..." in caseStudies [Drasil does a better job of being consistent in capitalization.  @szymczdm and I discussed this benefit of Drasil just yesterday.  Please change the case study to match the Drasil version.]

**Comment by elwazana** [comment] 2018-07-11 18:51
@smiths Hello Dr. Smith, I just wanted to ask you if the solution is ok for the third task in the checklist:

When adding the definitions for AR<sub>max</sub>, AR, GTF, LDF, LR, LSF, NFL, TNT. The table would fall behind the next pages back:
![image](https://user-images.githubusercontent.com/35268928/42593165-b8002422-8519-11e8-9114-17a56d8b6c7f.png)

I can fix  it, but it requires me to hardcode it to be two separate tables:
![image](https://user-images.githubusercontent.com/35268928/42593112-8dfbedbe-8519-11e8-9041-53ac712832be.png)

**Comment by smiths** [comment] 2018-07-11 19:18
We don't want to hard-code two tables.  This sounds like a LaTeX issue.  longtable should appropriately split between two pages automatically.  I don't know what tabular environment is being used, but look for one that automatically splits between tables.

Since you and @samm82 are both currently looking at GlassBR, please make sure to coordinate your efforts.

**Comment by elwazana** [comment] 2018-07-11 20:12
This is the finished caseStudies Table fo Symbols:
![image](https://user-images.githubusercontent.com/35268928/42596857-128fcc7a-8525-11e8-91aa-3473cd62aff5.png)

**Comment by elwazana** [comment] 2018-07-11 20:15
This is the commit with the changes: 
https://github.com/smiths/caseStudies/commit/f6fb98c7cb20b2cb44de3fcb9b878e2e68ccd891

**Comment by smiths** [comment] 2018-07-11 20:44
Thank you for updating the table of symbols.  Looks good.  This edit highlights other changes to the case study SRS that need to be made.  

In thinking about it further, we may have made a mistake in changing a and b to SI (m instead of mm).  What units does the Drasil code use?  (My stack is currently broken so I cannot easily generate the documentation).  I would rather use SI standard units throughout, but this change has a cascading effect.  Many equations will need to be changed and the MIS will need to be changed.

If the Drasil code for GlassBR is assuming mm for a, b, h etc, then we should stick with this decision.  This will mean backing out the changes to a, b and h in the table of symbols.  If the Drasil code already uses m, then we'll have to update the case study to use consistent units.

Currently q is in kPa in the case study.  Is this the case in the Drasil code too?  Eventually I would like it in Pa, but we shouldn't make this change when there are so many other changes going on at the same time.

Based on your feedback we can decide what to do with the units.  The goal is to select the course that has the least amount of effect.

**Comment by elwazana** [comment] 2018-07-11 22:15
@smiths Comparison report:

1. a,b, and h have (m) listed as their units in Drasil.

2. q has kPa listed as its units in Drasil.

3. One difference I noticed is that E has different units, in the manual its kPa, but in Drasil its Pa.
(Top Manual | Bottom Drasil)
![image](https://user-images.githubusercontent.com/35268928/42602052-dc8cfb5a-8535-11e8-9b97-72919996532c.png)
![image](https://user-images.githubusercontent.com/35268928/42602076-eecf6b4a-8535-11e8-8ba7-74e265523886.png)

4. As a note, SI units aren't used for t, d<sub>max</sub>, and d<sub>min</sub>, which have (mm) listed as their units

**Comment by smiths** [comment] 2018-07-11 22:24
Thank you @elwazana.  Are the units for a, b and h consistent throughout the document?  Several equations, like the equation for B, depend on a, b and h.  If the units for a, b and h are in mm, then the equation includes a conversion factor.  If the units are in m, then the conversion factor isn't there.  Hopefully Drasil is correct and a, b and h are not converted.  I seem to recall we went through the Drasil version and made everything into the base units.  That would also explain why E would be in Pa in the Drasil version.  I'm surprised that q is in kPa though, since that would make those equations that involve q potentially inconsistent.  It is possible that the original source material included the unit conversion.

**Comment by elwazana** [comment] 2018-07-12 13:43
@smiths Hello Dr. Smith, a, b, and h seem to consistently appear as (m)
Drasil:
![image](https://user-images.githubusercontent.com/35268928/42636138-fb95856e-85b5-11e8-99de-baec8f49c552.png)

However, the manual seems to have a conversion factor from (mm -> m), which should be changed now that a, b, and h have been defined as being (m) in the table fo symbols.
There also seems to be a conversion factor for E from (kPa -> Pa), which if you decide to go with Pa as the defined unit will need to be changed where ever E is used in the Manual.
Manual:
![image](https://user-images.githubusercontent.com/35268928/42636295-6a792742-85b6-11e8-9e6d-fe33b4c60da3.png)

For q, it seems to be consistently used as kPa with no conversion factor for both Drasil and the Manual.
Drasil:
![image](https://user-images.githubusercontent.com/35268928/42636395-b871ccc4-85b6-11e8-9478-cd6b410be90e.png)

Manual:
![image](https://user-images.githubusercontent.com/35268928/42636429-cd3c45a8-85b6-11e8-92e2-88e23bb5a157.png)

**Comment by smiths** [comment] 2018-07-12 14:00
Great summary @elwazana.  Unfortunately this makes things more confusing and muddled.  The conversion factor seems to be there when a and b are in mm and not there when a and b are in m.  Having E in Pa and q in kPa is not consistent.

We need to sort this out once and for all.  Can you please find the original equations in the source material, along with the units used for those equations.  The source material should all be in the repo.  We need to make sure that our choices are correct.  Once we have this information, we can decide the best course of action.  I still prefer everything in standard units: m, Pa, etc., but if this makes the equations too awkward, we might go another route.

**Comment by elwazana** [comment] 2018-07-12 14:06
@smiths Just a quick question so I don't accidentally look over the wrong document, by source material do you mean in the src folder?

**Comment by smiths** [comment] 2018-07-12 14:17
Did you look in the src folder?  😄  The src folder is code.  If there is a mistake in the requirement, it will be in the code too.  The source information is given in the SRS in the Source field.  You can find the documents that matter in the refs folder in the repo.

**Comment by elwazana** [comment] 2018-07-12 16:41
@smiths Hello Dr. Smith, the original equations seem to be the ones in Drasil, although the parts I circled in red don't appear in the Drasil/Manual versions.

Drasil:
![](https://user-images.githubusercontent.com/35268928/42636395-b871ccc4-85b6-11e8-9478-cd6b410be90e.png)


Origianl:
![image](https://user-images.githubusercontent.com/35268928/42646758-d6eb547c-85cf-11e8-80ed-a9fe7a0d92d4.png)

Drasil:
![](https://user-images.githubusercontent.com/35268928/42636138-fb95856e-85b5-11e8-99de-baec8f49c552.png)

Original:
![image](https://user-images.githubusercontent.com/35268928/42646881-2d119f46-85d0-11e8-9720-16e838873fed.png)

**Comment by elwazana** [comment] 2018-07-12 16:43
@smiths Hello Dr. Smith, the original equations seem to be the ones in Drasil, although the parts I circled in red don't appear in the Drasil/Manual versions.

Drasil:
![](https://user-images.githubusercontent.com/35268928/42636395-b871ccc4-85b6-11e8-9478-cd6b410be90e.png)


Original:
![image](https://user-images.githubusercontent.com/35268928/42646758-d6eb547c-85cf-11e8-80ed-a9fe7a0d92d4.png)

Drasil:
![](https://user-images.githubusercontent.com/35268928/42636138-fb95856e-85b5-11e8-99de-baec8f49c552.png)

Original:
![image](https://user-images.githubusercontent.com/35268928/42646881-2d119f46-85d0-11e8-9720-16e838873fed.png)

**Comment by smiths** [comment] 2018-07-12 17:38
Great investigation @elwazana.  I was starting to doubt that we could sort this out and be sure to be consistent.  So many changes are going on concurrently and some of the previous students (and myself) weren't as careful as we should have been.  With your information we can make sure that the Drasil version is correct for the units, and then propagate these corrections to the case study version.

For the dimensionless load (q hat), I see how we can fix things to make it correct and consistent.  Please make the following modification to the Drasil version (and subsequently to the Case Study version):

- q should be Pa (if q is in kPa and E is in Pa there will be an error.  q is dimensionless so the units are supposed to cancel.  If both q and E are in Pa, or both in kPa, it will work, but if the units are different we have an extra 1000 floating around.  Since we want the units to be in the standard units, let us change everything to Pa
- add a note (under Notes) that this formula is for a single lite (A5) so LSF = 1.0.  This equation was simplified from the original source because LSF is assumed to be 1.0 in A5 (from the Case Study numbering, in case they are different).  We didn't explain this well in the original document though, so you, and anyone else looking at the equation, are going to wonder what is happening.  If we add traceability to the assumption, then the consequences of changing this assumption are clear.  (Currently changing A5 does not explicitly show an impact on the data definition.  Good catch!)
- Under the Source field, please add a reference to the source that you used for the experts above.  I'm sorry that the Source field was previously empty.  This should have been easier for you.  That is the entire point of the Source field!  Now we have the chance to correct this mistake.  Even better, please include the Equation number with the source.  We should make this as easy as possible to see where the information came from.

We should leave the dimensions (a, b and h) in m.  Technically it doesn't matter, as long as they are consistent, since the units will cancel out.  However, for reasons we have discussed previously, I prefer m.

For the risk of failure, the Drasil version looks almost right.  Please make the following changes:

- Remove the factor of 1000 from the equation (in front of E).  (The fact that this slipped through is frustrating.  At least when Drasil is working properly changes like this will easily propagate through all of the artifacts.  Too bad we have to do so much manually right now.)
- For the Source [4] please add the equation number that you used.  As I mentioned above, it is ideal if we can have full traceability.  Not just to the document, but to the parts of the document that we are using.

As far the part circled in red, we shouldn't have to worry.  The value of J is calculated in DD4 (Stress Distribution Factor) (Case Study Version).

You might want to create a new issue for these changes, so that it doesn't get too lost in the mix.

Thank you again for the investigation.  I don't like that it was necessary, but I do like that it worked fairly smoothly.  😄

**Comment by elwazana** [comment] 2018-07-12 20:32
@smiths Hello Dr. Smith, for the source field of the segments I retrieved those from:
![image](https://user-images.githubusercontent.com/35268928/42657429-215b53d4-85f0-11e8-9894-d52922532c7f.png)
The document is not in the references for GlassBR, and you can't reference that isn't defined somewhere in the example (the references already there are defined as `Contents`). 
So how should I put it in the source field?

Here are the other two requested changes related to q:
![image](https://user-images.githubusercontent.com/35268928/42657542-81611b2e-85f0-11e8-894a-5aa5ecb7a171.png)

**Comment by smiths** [comment] 2018-07-12 21:21
I hadn't realized that you used Manuel's document, but this isn't a problem.  You can create a bib entry for it and then reference that.  The better job we do with traceability to the actual source of the information, the more useful the documentation is.  If you need an example of creating bibliographic information for a reference like this, you can follow the Marilyn Lightstone reference for SWHS.

The citation for the definition of q hat should be in the Source field, not in the Notes field.

If you have problems with adding new bib information, I'm pretty sure your colleagues can help you.

**Comment by elwazana** [comment] 2018-07-13 15:05
@smiths Hello Dr. Smith, I've moved the citations for the definition of q hat and I've created and cited the appropriate Document reference:
![image](https://user-images.githubusercontent.com/35268928/42698501-179efc28-868c-11e8-8279-9417eec7e069.png)
![image](https://user-images.githubusercontent.com/35268928/42698524-25a7deac-868c-11e8-8c9d-6eda7ff900c8.png)

With regards to the equation numbers, is there a format you have in mind for how they should appear in the source field?

**Comment by smiths** [comment] 2018-07-13 15:36
Great to see the source updated.  What does [glassLite] mean?  I would think you would just have the [5]?  As far as referencing the equation, I would think you would have something like:

[5, Eq. 13]

I made up the equation number.  You would actually want to look at the source to see the real number.

**Comment by elwazana** [comment] 2018-07-13 21:20
@smiths Hello Dr. Smith, I was able to generate the following:
![image](https://user-images.githubusercontent.com/35268928/42713304-01c1b306-86bd-11e8-9371-900ba70480d9.png)
![image](https://user-images.githubusercontent.com/35268928/42714145-0ec23dca-86c0-11e8-866a-36e62b77e896.png)

However, to do this I needed to revert a change the yuzhi branch had once it was merged into master earlier today. The change had a "FIXME" placed inside all the source fields in all the tables, my reversion now causes all the source fields to be empty or filled, i.e: 
![image](https://user-images.githubusercontent.com/35268928/42714210-612bcb44-86c0-11e8-8edf-eeeb6aee056d.png)

This is the commit from the yuzhi branch that I reversed: f70bb0a32241506e0a1f69f18ca29e52bc9c4d63

**Comment by smiths** [comment] 2018-07-14 03:59
@elwazana, you should discuss this with @halonazhao and probably @niazim3.  We might have to wait for the FIXME before updating this.  You probably should back out your change.

Can you please make a new issue for adding this information to Drasil.

Also, please make an issue for doing this update in the case study version as well.  You should be able to proceed with making this change in the case study version.  For citations that have notes you can include the information in square brackets before the citations.  `(\cite[Eq.~7]{WhateverRef5Is})`

**Comment by elwazana** [comment] 2018-07-16 14:49
@smiths Hello Dr. Smith, it seems like the "FIXME" was just a placeholder and not referring to an existing problem that needs resolution, so should I go through with my changes?

**Comment by samm82** [comment] 2018-07-16 21:16
@elwazana @smiths I just noticed some issues with the Drasil PDF:

1) AR should come before AR<sub>max</sub>, as the shortest words come first in alphabetical order,  and to match the (correct) rest of Drasil
![AR](https://user-images.githubusercontent.com/35857611/42783460-215cadec-891a-11e8-9419-3f04093817db.png)
Example of correct:

![w](https://user-images.githubusercontent.com/35857611/42783545-5b4d41e2-891a-11e8-8ed9-6273ef03e8e4.png)

2) Stand off distance (SD) is listed twice:
![SD](https://user-images.githubusercontent.com/35857611/42783595-7bad847e-891a-11e8-8bfe-9512bb18cc99.png)

To match the first point, the second one should be removed.

These issues don't occur in caseStudies

**Comment by smiths** [comment] 2018-07-17 04:12
@elwazana, you need to start splitting this issue up.  It is far too long and there are far too many topics.  It will be very difficult to find any of the specific sub-issues in the future if we are searching by issue titles.

**Comment by elwazana** [comment] 2018-07-19 15:47
@smiths Hello Dr. Smith, should I go through with the reintroduction of the source field for the Data Definitions? As I mentioned above the "Fixme" currently there is just a placeholder.

**Comment by smiths** [comment] 2018-07-23 13:41
Agreed.

**Comment by samm82** [comment] 2019-05-01 17:10
Not sure if this and #130 can be closed. It looks like they are based on the commit/PR history.

**Comment by smiths** [comment] 2019-05-01 19:14
Again, this issue is not one issue, but many issues combined.  Even worse, the conversation shifts to other topics.  We have to really try to stop doing this.  :smile:.

It seems this issue is about updating the case study (manual) version.  I think we are fine to close this issue, since the changes seem to have been made, and further maintenance of the case studies is not a high priority at this time.

As far as #130, that issue should be discussed under that issue, not under this one.  :smile:

**Closed by smiths** 2019-05-01 19:14 UTC
