### ISSUE TITLE
Add system context section to GlassBR example

### ISSUE THREAD

**Issue by deviprasad135** [JacquesCarette/Drasil#574] opened 2018-06-04 17:52 UTC
GlassBR is missing system context section. Update GlassBR SRS by adding system context section into it.

**Comment by samm82** [comment] 2018-07-18 14:53
From #820:

The section "System Context" is missing from the Drasil (left) PDF entirely, in the table of contents and the document itself. Also, all references to other subsections of "General System Description" are shifted, due to the missing section.

![system context](https://user-images.githubusercontent.com/35857611/42574759-31c983e8-84ed-11e8-8b6b-28ea8fbe525f.png)

<ins>Example of shifted references:</ins>
![refs](https://user-images.githubusercontent.com/35857611/42574913-95341b78-84ed-11e8-9531-0edd0140f415.png)

---

This is what is missing:

![system context caseStudies](https://user-images.githubusercontent.com/35857611/42574849-6df6e4c8-84ed-11e8-90dc-49a2aef9870e.png)

**Comment by deviprasad135** [comment] 2018-07-18 14:57
@samm82 , I have added this but i dint push it yet. I will push it in a while.

**Comment by samm82** [comment] 2018-07-18 14:58
Sounds good - I only added this because I closed the original issue I made because it was a duplicate of this one, and didn't want this summary to be lost - thanks!

**Comment by niazim3** [comment] 2018-07-18 22:10
@deviprasad135 With the merge of #909, you can use the newly added `SysContxt` section description language instead of `Verbatim` in `mkSRS`; that way, GlassBR will remain as an example without `Verbatim`.

**Closed** 2018-08-01 21:56 UTC
