### ISSUE TITLE
PD Controller SRS link on website leads to 404

### ISSUE THREAD

**Issue by balacij** [JacquesCarette/Drasil#3585] opened 2023-08-03 16:24 UTC
On the main [Drasil website](https://jacquescarette.github.io/Drasil/), the link to the PD Controller SRS is broken.

The link: https://jacquescarette.github.io/Drasil/examples/pd_controller/SRS/srs/PD_Controller_SRS.html

**Comment by samm82** [comment] 2023-08-04 01:15
Dupe of #3565 😉

**Closed by samm82** 2023-08-04 01:15 UTC
Labels: bug, artifacts

**Comment by balacij** [comment] 2023-08-04 15:50
Whoops! Thank you @samm82 :smile:
