### ISSUE TITLE
`drasil-docLang` should allow us to have SRS documents with empty traceability matrices

### ISSUE THREAD

**Issue by balacij** [JacquesCarette/Drasil#3428] opened 2023-05-16 17:09 UTC
Similar to #3427, in the name of decreasing the time to gratification (seeing tangible artifacts) when developing new projects, we should remove the restriction (from `drasil-docLang`) that says that each SRS document must have a non-empty traceability matrix.

Similar to #3427, I [hacked in a solution](https://github.com/JacquesCarette/Drasil/compare/master...balacij:Drasil:beamBending?expand=1#diff-404217f13ec9aff55d416f24e2ea76ad2f809455735b5d3f3b128d0f6e11440c). We should do this properly now, however (i.e., one that creates appropriate text and doesn't generate an empty table).

Contributes to #3326, #3356

**Comment by samm82** [comment] 2023-05-16 17:11
Is this a dupe of https://github.com/JacquesCarette/Drasil/issues/3353 (and what is the status of your potential fix there?)

**Comment by samm82** [comment] 2023-05-16 17:21
I'd be fine with it, but I'm not sure if this ticket really describes the issue "correctly". If by "empty" you mean "having no 'X's in it", we can already do that in Drasil! The issue arises when we don't have a type of information that is needed to generate a traceability matrix; allowing for these matrices to be built the way this suggests seems like it could be generating a matrix with only column headers and no rows, for example. I think the correct fix for this issue is to only generate traceability matrices that the required information is present for (along with the corresponding descriptive text).

Also, is there a way you could include a link that doesn't automatically try and open a PR? 😅

**Comment by balacij** [comment] 2023-05-16 17:25
I meant "empty" as in no rows/columns. Sure, that sounds good. Thank you!

Re: PR: I wanted it to show the whole comparison for easy viewing, I'm not sure if we can remove the autogenerated PR.

**Closed** 2023-05-26 18:00 UTC
Labels: enhancement, easy
