### ISSUE TITLE
Implement Vector Scaling

### ISSUE THREAD

**Issue by JacquesCarette** [JacquesCarette/Drasil#3166] opened 2022-11-30 19:53 UTC
Fixing #3164 needs scaling a vector (and likely many others will need it too).

**Comment by balacij** [comment] 2022-11-30 20:18
Duplicate of #3166 ? I think we need a few extra operations around vectors too.

**Comment by JacquesCarette** [comment] 2022-11-30 20:36
You've link the issue to itself as a duplicate.

**Comment by balacij** [comment] 2022-11-30 21:44
That's funny. #3149

**Closed** 2022-12-01 19:55 UTC
