### ISSUE TITLE
Review Chapter 3 of Dan's Thesis

### ISSUE THREAD

**Issue by szymczdm** [JacquesCarette/Drasil#3984] opened 2024-11-11 00:14 UTC
Please review Chapter 3 (Our Process) of my thesis found on the `Writing` branch under People/Dan/Thsis/Draft/ (The file `Thesis_Main.pdf` should be up-to-date wrt changes we discussed.

The file for Chapter 3 is `process.tex`

**Comment by JacquesCarette** [comment] 2024-12-11 21:14
(Closing as I've done the review, at a high level; we can keep conversing here, even if the issue is closed.)

**Closed by JacquesCarette** 2024-12-11 21:14 UTC
