### ISSUE TITLE
SRS document formatting problem for long labels

### ISSUE THREAD

**Issue by deemaalomair1** [JacquesCarette/Drasil#1877] opened 2019-09-12 18:47 UTC
@smiths  There is a presentation problem I faced when I download the PDF. Some letters in some  sections are sifted toward the left-side of the page, so not all the letters appear clearly and I could not understand the word. 
sections effected are:
4.1.3 Goal statements , 4.2.1 Assumptions , 5.1 Functional Requirements, 6 Likely Changes and 7 Unlikely Changes. 

Attached one page as an example:
![presentation_issue](https://user-images.githubusercontent.com/45468077/64811797-fa5b1180-d56b-11e9-9973-0a9d515fd88a.png)

**Comment by smiths** [comment] 2019-09-13 12:36
Thank you @deemaalomair1.  You are correct about the formatting of the labels.  We know about this problem, but have let it remain in the interest of pursuing other priorities.  Having said that, we do not have any open issues related to this formatting issue, so I will keep your issue in the issue tracker, as a future enhancement to Drasil.

Your issue is for SWHS, but the formatting issue actually applies to all of the Drasil examples.  Therefore, I will rename your issue as well.

@deemaalomair1, this is a nice example of an issue.  I especially like that you included a screen shot so that the issue is self-contained.  My only advice for next time is that the issue should have been assigned to me.  There is a drop-down option for Assignees on the right hand side of this window.

**Comment by deemaalomair1** [comment] 2019-09-13 15:32
Thank you Dr.Smith for the quick respond. Actually i tried to assign the issue , but it seems that i do not have the privilege to assign . The assignees option is not open for me. @smiths

**Comment by smiths** [comment] 2019-09-13 15:35
Now that you mention it @deemaalomair1, that makes sense, since you are not a collaborator on this project.  Thank you for letting me know.  Since you cannot assign the issue, you did the next best thing, you at-ed me in the body of your issue.

**Comment by BilalM04** [comment] 2024-07-26 16:29
This issue caught my eye. The lists with labels that flow off the page in LaTeX are of type `Simple` in Drasil. See [here](https://github.com/JacquesCarette/Drasil/blob/6c4ac7614f805a6c5af26479209f40f9ff655bd0/code/drasil-lang/lib/Language/Drasil/Document/Core.hs#L20-L25) for the different list types. Looking at the [Haddock docs](https://jacquescarette.github.io/Drasil/docs/drasil-lang-0.1.60.0/Language-Drasil.html#t:ListType), `Simple` lists should be rendered as "Title: item".

In the Haddock docs, it says `Desc` items should be rendered as "**Title: Item**" (all bold), which I *believe* should be "**Title:** Item" (only Title is bold). Correct me if I'm wrong.

---

To address the issue mentioned, the `Desc` list type in LaTeX is rendered using the `\begin{description}` environment, which automatically bolds the titles. Currently, the `Simple` items are rendered using the `\begin{itemize}` environment, resulting in the misaligned rendering observed in the original post. Since the `Simple` list type is essentially the same as `Desc` but without the bold titles, we can use the description environment with an argument to achieve the desired formatting.

```LaTeX
\begin{description}[font=\normalfont]
...
\end{description}
```

I manually tested the code above, and it works as expected. Additionally, the argument (`font=\normalfont`) does not override any text formatting within the list items themselves (such as `\textbf`), it will only remove the bold off the title. The `Simple` lists will render as follows:


![image](https://github.com/user-attachments/assets/6a9e9b22-f535-4a4d-81f7-10a1e0bde12e)

[Here](https://jacquescarette.github.io/Drasil/examples/projectile/SRS/PDF/Projectile_SRS.pdf#page=25) is the original for reference.

**Comment by smiths** [comment] 2024-07-26 18:03
Great investigation @BilalM04.  I like your proposed fix of using the description environment.  That is what I tend to use in my own manually created LaTeX documents.  Let's go ahead and make this change.

**Closed** 2024-07-27 09:09 UTC
Labels: bug, artifacts
