### ISSUE TITLE
Table length ecxeeds page lengh. 

### ISSUE THREAD

**Issue by yanxuanm** [JacquesCarette/Drasil#2239] opened 2020-09-16 00:01 UTC
@smiths 

GamePhysics_SRS, page 33 & 34, table length ecxeeds page length.  Page 39 to 42, table width ecxeeds page width. 

Texts in page 33& 34 those two tables also covered page index.

**Comment by smiths** [comment] 2020-10-05 03:16
Thank you @yanxuanm.  This issue has been raised elsewhere, so I will close this instance of it.  (The issue is a consequence of generating LaTeX code.)

**Closed by smiths** 2020-10-05 03:16 UTC
