### ISSUE TITLE
Renaming in GlassBR

### ISSUE THREAD

**Issue by danscime** [JacquesCarette/Drasil#1297] opened 2019-05-09 14:49 UTC
Need to rename:

glassBR_srs to srs
&
glassBR_code to code

via comments on the two commits:
dea4a71a2ff554453e81acb4e88261814d428cab
and
c09fe3171c3a4316842c7bf9355c8702b39c8c8a

**Comment by samm82** [comment] 2019-05-21 16:53
Closed as duplicate of #1267

**Closed by samm82** 2019-05-21 16:53 UTC
