### ISSUE TITLE
Projectile Case Study SRS - External / User Interfaces

### ISSUE THREAD

**Issue by peter-michalski** [JacquesCarette/Drasil#1885] opened 2019-09-14 15:52 UTC
@smiths 

A section outlining external / user interfaces does not appear in the srs document - a quality attribute introduced in the reading "A rational document driven design process for scientific computing software." Would this be necessary for this type of case study?

**Comment by smiths** [comment] 2019-09-17 15:47
@peter-michalski, I'm not sure exactly what issue you are describing here.  If the issue is about having a specification of the user interface, that is intentionally left out.  The requirements are intended to be abstract; we leave the design of the user interface to the design stage.  At the requirements stage we aim to have nonfunctional requirements that specify what we mean by a good user experience.  The design stage is then intended to create something that will meet those requirements.  (I do not believe that the Projectile example has nonfunctional requirements.  That is something we intend to add in the future.)

I'm going to close this issue, but if I misunderstood, please clarify and reopen it.

**Closed by smiths** 2019-09-17 15:47 UTC
